import React, { useState, useEffect } from "react";
import Styles from "../Styles/Content.module.css";
import Navbar from "../Components/Navbar";
import Header from "../Components/Header";
import About from "../Components/About";
import Skills from "../Components/Skills";
import { SkillsIntro } from "../Components/Skills";
import Services from "../Components/Services";
import { ServicesIntro } from "../Components/Services";
import Projects, { ProjectIntro } from "../Components/Projects";
import Contact from "../Components/Contact";
import Footer from "../Components/Footer_";
import logo1 from "../Assets/logo1.png";
import logo2 from "../Assets/logo2.png";
import logo3 from "../Assets/logo3.png";
import logo4 from "../Assets/logo4.png";
import logo5 from "../Assets/logo5.png";
import logo6 from "../Assets/logo6.png";
import logo10 from "../Assets/logo10.png";
import logo9 from "../Assets/logo9.png";
import logo7 from "../Assets/logo7.png";
import logo11 from "../Assets/logo11.png";
import logo12 from "../Assets/logo12.png";
import logo13 from "../Assets/logo13.png";
import cleanCode from "../Assets/cleanCode.png";
import responsive from "../Assets/responsive.png";
import frontend from "../Assets/frontend.png";
import webDesign from "../Assets/webDesign.png";
import restApi from "../Assets/restApi.png";
import webDev from "../Assets/webDev.png";
import advice_gen_app from "../Assets/advice_gen_app.png";
import Rest_countries_API from "../Assets/Rest_countries_API.png";
import signUpForm from "../Assets/signUpForm.png";
import BmiApp from "../Assets/BmiApp.png";
import Dialog from "@mui/material/Dialog";

const skillList = [
  {
    image: logo1,
    content: "REACT",
  },
  {
    image: logo2,
    content: "TAILWIND",
  },
  {
    image: logo3,
    content: "REDUX",
  },
  {
    image: logo9,
    content: "MUI",
  },
  {
    image: logo4,
    content: "HTML5",
  },
  {
    image: logo5,
    content: "CSS3",
  },
  {
    image: logo6,
    content: "JAVASCRIPT",
  },
  {
    image: logo10,
    content: "GIT",
  },
  {
    image: logo7,
    content: "NODE.JS",
  },
  {
    image: logo11,
    content: "EXPRESS.JS",
  },
  {
    image: logo12,
    content: "MONGO DB",
  },
  {
    image: logo13,
    content: "FIGMA",
  },
];

const ServiceList = [
  {
    image: frontend,
    heading: "FRONTEND DEVELOPMENT",
    content:
      "High quality development of sites with extreme attention to details at a professional level.",
  },
  {
    image: responsive,
    heading: "RESPONSIVE DESIGNS",
    content:
      "Quality and effective development of sites to render and adapt to any given device.",
  },
  {
    image: cleanCode,
    heading: "CLEAN CODE",
    content:
      "Clean code practice to maintain the main concepts and skills needed to use code and computational thinking.",
  },
  {
    image: webDesign,
    heading: "WEB DESIGN",
    content:
      "Mastermind the process of building the elements of a website, which entails the overall look and feel of the website.",
  },
  {
    image: restApi,
    heading: "RESTFUL SERVICES AND APIs",
    content:
      "Creation and consumption of RESTful (Representational State Transfer) Web services and APIs.",
  },
  {
    image: webDev,
    heading: "WEB DEVELOPMENT",
    content:
      "Meticulous development of websites that are up to standard and can render properly on any web browser.",
  },
];

const projectLists = [
  {
    title: "Advice Generator App",
    description:
      "This project is centered around API. I implemented data fetching from Advice Slip API. This application gives out over ten million pieces of advice, and this is generated by clicking the dice icon. Built with HTML, CSS and JavaScript.",
    githubRepo: "https://github.com/chilara/advice-gen-app",
    liveSite: "https://chilara.github.io/advice-gen-app/",
    image: <img src={advice_gen_app} alt="" style={{ height: "100%" }} />,
  },
  {
    title: "REST Countries API",
    description:
      "This Project is basically a website that displays country data. You can also view more detailed information about a particular country. User can also toggle color scheme between light and dark mode. Built with react, styled-components, tailwind, redux, Material UI.",
    githubRepo: "https://github.com/chilara/rest-country-api",
    liveSite: "",
    image: <img src={Rest_countries_API} alt="" style={{ height: "100%" }} />,
  },
  {
    title: "BMI Calculator",
    description:
      "BMI calculator (Body Mass Index) is built for the health-tech sector. It is a way of estimating the amount of body fat. This product is used to calculate the risk of heart disease and check if an individual has a healthy body weight. Built with HTML, CSS and JavaScript.",
    githubRepo: "https://github.com/chilara/BMI-calculator",
    liveSite: "https://chilara.github.io/BMI-calculator/",
    image: <img src={BmiApp} alt="" style={{ height: "100%" }} />,
  },
  {
    title: "Todo-List App",
    description:
      "This is a web application that is used to document list of activities or events to be done. I implemented the use of React-Router as a means of navigation, used useState to manage states. Built with React, CSS, Formik library.",
    githubRepo: "https://github.com/chilara/todo-list",
    liveSite: "",
    image: "",
  },
  {
    title: "BootCamp Sign-up form",
    description:
      "This Project is a Landing page with a sign up form, aimed at client-side validation using JavaScript. It has a very clean UI, seamless with both desktop and mobile version. Built with HTML, CSS and JavaScript",
    githubRepo:
      "https://github.com/chilara/medie-query-Zuri-task/tree/gh-pages",
    liveSite: "https://chilara.github.io/medie-query-Zuri-task/",
    image: <img src={signUpForm} alt="" style={{ height: "100%" }} />,
  },
];

const Home = () => {
  const [open, setOpen] = useState(false);

  const handleOpen = () => {
    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
  };

  const [pdfFile, setPdfFile] = useState("");

  useEffect(() => {
    const file = require("../Assets/Resume.pdf");
    setPdfFile(file);
  }, []);

  return (
    <section>
      <div className={Styles.headerImage}>
        <main>
          <Navbar />
          <Header />
        </main>
      </div>
      <About handleOpen={handleOpen} />
      <div className={Styles.skillsContainer}>
        <SkillsIntro />
        <div
          className={Styles.SkillsFlex}
          style={{
            display: "flex",
            flexWrap: "wrap",
            justifyContent: "space-between",
          }}
        >
          {skillList.map((items) => (
            <Skills image={items.image} content={items.content} />
          ))}
        </div>
      </div>
      <div className={Styles.ServicesContainer}>
        <ServicesIntro />
        <div
          className={Styles.ServicesFlex}
          style={{
            display: "flex",
            flexWrap: "wrap",
            justifyContent: "space-between",
          }}
        >
          {ServiceList.map((items) => (
            <Services
              image={items.image}
              heading={items.heading}
              content={items.content}
            />
          ))}
        </div>
      </div>
      <div className={Styles.ProjectIntro}>
        <ProjectIntro />
        {projectLists.map((items, index) => (
          <Projects
            title={items.title}
            description={items.description}
            githubRepo={items.githubRepo}
            liveSite={items.liveSite}
            image={items.image}
            even={index % 2 === 0 ? true : false}
          />
        ))}
      </div>
      <Contact />
      <Footer />
      <Dialog
        onClose={handleClose}
        open={open}
        className={Styles.DialogContainer}
      >
        <div style={{ height: "80vh" }}>
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              height: "100%",
            }}
          >
            <object data={pdfFile} style={{ height: "600px", width: "80vw" }}>
              My CV
            </object>
          </div>
        </div>
      </Dialog>
    </section>
  );
};

export default Home;
